Update changes to fix failing tox.ini test
Minor and Basic Update to fix failing tox.ini test
home/runner/work/lwm2m_server/lwm2m_server/doc/source/documentation.rst:199:
ERROR: Document or section may not begin with a transition.

Signed-off-by: Akarshan Kapoor <data.akarshan@icloud.com>